FROM alpine:3.9
RUN apk add --update --no-cache curl postgresql tzdata
COPY run.sh /usr/bin/run.sh
COPY /go/src/go-crond/go-crond /usr/bin/go-crond
RUN rm -rf /etc/localtime && mkdir -p /usr/share/crond && \
touch /etc/localtime /etc/timezone && \
chown 1001 -R /etc/localtime /etc/timezone /usr/share/crond && \
chgrp -R 0 /etc/localtime /etc/timezone /usr/share/crond && \
chmod +x /usr/bin/go-crond /usr/bin/run.sh && \
chmod -R g=u /etc/localtime /etc/timezone /usr/share/crond /usr/bin/run.sh 
USER 1001
ENTRYPOINT ["/usr/bin/run.sh"]
CMD ["/usr/share/crond"]

